### PR TITLE
Change color to conform to 5c branding

### PR DESCRIPTION
**Pull request by mmazanec22**
Background was generic gray, is now 5th column purpleish

### CODE REVIEW

**Comment by csavage1994** [comment]
So I was going to test this out, I went to `kibana_root/src/public/views/chrome.jade` and added `link(rel="stylesheet", type="text/css", href="https://rawgit.com/5thColumn/kibana5-loading-screen/master/kibana-welcome.css")` On line 106 right under `.kibanaWelcomeLogo` (there was no `.kibanaWelcomeLoader in the file), and I'm still getting the default loading screen, am I doing something wrong?

**Comment by mmazanec22** [comment]
Yep, but only because my instructions sucked.  You can just add the line at the end.  I'll fix this.  Should I add a readme to this repo?

**Comment by heronblade** [comment]
should it be `src/ui/views/chrome.jade`?  I don't have a `src/ui/public/views` folder

**Comment by mmazanec22** [comment]
Yep.  Whoops.  I'm about to add some JS, so lemme just close this PR and re-make it in a bit

**Pull request closed without merging**
